import subprocess
import time
import os
import glob
import numpy as np
from concurrent.futures import ProcessPoolExecutor

# -------- USER CONFIG --------
# Path to the .dat files generated by prepsubband
DAT_PATTERN = "benchmark_output_prepsubband/*.dat"
DAT_FILES = sorted(glob.glob(DAT_PATTERN))

# Accelsearch Parameters
ZMAX = 0      # Change as needed (e.g., 50, 100)
NUMHARMS = 8  # Number of harmonics to sum
CORE_LIST = [1, 4, 8, 16]

# ----------------------------

if not DAT_FILES:
    raise FileNotFoundError(f"No .dat files found in {DAT_PATTERN}. Run prepsubband first!")

# Filter out the .inf files to make sure we only have .dat
DAT_FILES = [f for f in DAT_FILES if f.endswith('.dat')]

# Helper to clean up output files between runs if desired
def cleanup_accel_files():
    for f in glob.glob("*.cand") + glob.glob("*.accelsearch*"):
        try: os.remove(f)
        except: pass

# ----------------------------
# Method 1: Internal (-ncpus)
# ----------------------------
def run_internal_accel(ncpus):
    start = time.time()
    
    # In internal mode, we process files one by one, 
    # but each file uses all ncpus for FFT math.
    for dat in DAT_FILES:
        cmd = [
            "accelsearch",
            "-ncpus", str(ncpus),
            "-zmax", str(ZMAX),
            "-numharm", str(NUMHARMS),
            dat
        ]
        # We run this synchronously because the parallelism is inside the command
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        
    return time.time() - start

# ----------------------------
# Worker for Method 2
# ----------------------------
def run_single_accel(dat_file):
    # This runs a standard single-core accelsearch
    cmd = [
        "accelsearch",
        "-zmax", str(ZMAX),
        "-numharm", str(NUMHARMS),
        dat_file
    ]
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)

# ----------------------------
# Method 2: External (Process Pool)
# ----------------------------
def run_external_accel(ncores):
    start = time.time()
    
    # We launch ncores processes at once, each handling one .dat file
    with ProcessPoolExecutor(max_workers=ncores) as executor:
        executor.map(run_single_accel, DAT_FILES)
        
    return time.time() - start

# ----------------------------
# Main Benchmark Loop
# ----------------------------
def main():
    results = []
    print(f"\n--- ACCELSEARCH Benchmark ({len(DAT_FILES)} files) ---\n")

    for cores in CORE_LIST:
        print(f"Testing with {cores} cores...")
        
        # Cleanup previous runs to avoid mixing results
        cleanup_accel_files()
        
        # Method 1
        t_int = run_internal_accel(cores)
        print(f"  Internal (-ncpus {cores}): {t_int:.2f}s")
        
        cleanup_accel_files()

        # Method 2
        t_ext = run_external_accel(cores)
        print(f"  External ({cores} workers): {t_ext:.2f}s")
        
        results.append((cores, t_int, t_ext))

    # Final Summary
    print("\n=== FINAL ACCELSEARCH RESULTS ===")
    print(f"{'Cores':<8} | {'Internal(s)':<12} | {'External(s)':<12} | {'Faster'}")
    print("-" * 55)
    for c, ti, te in results:
        faster = "Internal" if ti < te else "External"
        print(f"{c:<8} | {ti:<12.2f} | {te:<12.2f} | {faster}")

if __name__ == "__main__":
    main()
